### ISSUE TITLE
Assistance in the implementation of BIP39 GPU 

### ISSUE THREAD

**Issue by ghost** [BilawalAhmed0900/BIPsImplementation#2]
Hello BilawalAhmed0900
I have a [BIP39](https://github.com/phrutis/BIP39) project with GPU support and checking against the address base through a bloom filter.
I'm not good at code CUDA trying to implement your code. 
Look at the CUDA source code, you can make it faster and more correct.

**Comment by BilawalAhmed0900** [comment]
Hy, I am also not good with CUDA itself. Since your codebase itself is very large, I am not able to provide assistance right now. You may send a detailed report at my email and I may look at your code in the future, till then, feel free to look at my code.
